apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.databaseURLSecret.name }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  database_url: {{ .Values.databaseURLSecret.database_url }}


